version: '3.8'

services:

  dashboard:
    container_name: dashboard
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn --workers=3 --threads=1 -b :8000 dashboard.main:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dashboard