name: test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.1/tailwindcss-linux-x64 -O tailwindcss
          chmod u+x tailwindcss
      - name: Build stylesheet
        run: nox -s tailwind
      - name: Run tests
        run: nox -t test
        env:
          DB_URL: ${{ secrets.DB_URL }}
      - name: Save code coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ matrix.os }}_${{ matrix.python-version }}.xml
          path: ./coverage.xml
      - name: Save test result file
        uses: actions/upload-artifact@v3
        with:
          name: test_result_${{ matrix.os }}_${{ matrix.python-version }}.xml
          path: ./test_result.xml
